//
// Created by Fedorov, Alex on 9/15/20.
//

#ifndef ANYWHERECHESS_PROMOTIONRESULT_H
#define ANYWHERECHESS_PROMOTIONRESULT_H

enum class PromotionResult {
    SUCCESSFUL, FAILED
};

#endif //ANYWHERECHESS_PROMOTIONRESULT_H
